version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=localhost
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_logs:/opt/emqx/logs
    networks:
      - emqx_network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=medorg
      - DOCKER_INFLUXDB_INIT_BUCKET=medical
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
    networks:
      - emqx_network

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - emqx
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - emqx_network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - emqx_network

volumes:
  emqx_data:
  emqx_logs:
  influxdb_data:
  grafana_data:

networks:
  emqx_network:
    driver: bridge